# Generated by Django 5.0.3 on 2024-04-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_address_user_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cart_number',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
