# Generated by Django 5.0.3 on 2024-05-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_cart_number_user_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_profile',
            field=models.ImageField(blank=True, null=True, upload_to='account'),
        ),
    ]
