# Generated by Django 5.0.3 on 2024-04-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productcomment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='confirmed_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
