# Generated by Django 5.0.1 on 2024-05-07 11:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_productcomment_user_dislike_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='user_dislike',
            field=models.ManyToManyField(related_name='user_disliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='user_liked',
            field=models.ManyToManyField(related_name='user_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
