# Generated by Django 5.0.3 on 2024-05-12 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_sold_alter_productcomment_user_dislike_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='product')),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='picture',
            new_name='main_picture',
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='user_dislike',
            field=models.ManyToManyField(blank=True, related_name='user_disliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='user_liked',
            field=models.ManyToManyField(blank=True, related_name='user_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='gallery_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productgallery'),
        ),
    ]
