# Generated by Django 5.0.3 on 2024-05-12 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_productgallery_rename_picture_product_main_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gallery_picture',
        ),
        migrations.AddField(
            model_name='productgallery',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
