# Generated by Django 5.0.3 on 2024-04-25 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=300)),
                ('receiver_num', models.CharField(max_length=11)),
                ('receiver_state', models.CharField(max_length=200)),
                ('receiver_city', models.CharField(max_length=200)),
                ('receiver_Postal_address', models.CharField(max_length=400)),
                ('receiver_Postal_code', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
