# Generated by Django 5.0.1 on 2024-05-10 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_comment',
            name='admin_respond',
            field=models.CharField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog_comment',
            name='user_dislike',
            field=models.ManyToManyField(blank=True, related_name='blog_disliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog_comment',
            name='user_liked',
            field=models.ManyToManyField(blank=True, related_name='blog_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
