# Generated by Django 5.0.3 on 2024-05-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_comment_admin_respond_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_comment',
            name='admin_respond',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
