# Generated by Django 5.0.3 on 2024-05-16 10:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_comment_admin_respond'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='main_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
