# Generated by Django 5.0.1 on 2024-05-21 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_main_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.blog_comment'),
        ),
    ]
